<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Model.aspx.cs" Inherits="Default2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <div id="siteTop" style="margin: 0px; padding: 0px; height: 32px; width: 1885px; border-bottom: 1px solid rgb(220, 215, 194);">
        <div class="siteTopBox" style="margin: 0px auto; padding: 0px; width: 1200px; max-width: 1200px; min-width: 1000px; height: 32px; line-height: 32px; font-size: 13px; color: rgb(140, 132, 123);">
            <div class="left" style="margin: 0px; padding: 0px; float: left;">
                天堂网 — 创建于2006年，大型网上纪念馆平台，绿色网上祭奠、网上扫墓</div>
            <div class="right" style="margin: 0px; padding: 0px; float: right; color: rgb(204, 204, 204);">
                <a class="red" href="http://www.tiantang6.com/login/" style="margin: 0px 10px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;">用户登录</a>|<a href="http://www.tiantang6.com/register/" style="margin: 0px 10px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">免费注册</a>|<a href="http://www.tiantang6.com/help/" style="margin: 0px 10px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">帮助中心</a></div>
        </div>
    </div>
    <div id="header" style="margin: 0px auto; padding: 0px; height: 118px; position: relative; width: 1200px; max-width: 1200px; min-width: 1000px;">
        <div class="logo" style="margin: 0px; padding: 5px 0px 0px;">
            <a href="http://www.tiantang6.com/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">
            <img alt="天堂网.网上纪念馆" src="http://www.tiantang6.com/images/logo.png" style="border: 0px;" /></a></div>
        <div class="headright" style="margin: 0px; padding: 0px; position: absolute; right: 0px; top: 35px;">
            <div class="topsearch" style="margin: 0px; padding: 0px;">
                <form action="http://www.tiantang6.com/memorial/search.html" class="search" method="Post" name="search" style="margin: 0px 10px 0px 0px; padding: 8px 0px 0px; font-size: 16px;">
                    查找纪念馆：<input class="search1" maxlength="20" name="searchkey" onfocus="if(this.value=='逝者姓名'){this.value='';}" style="margin: 0px; padding: 0px 0px 0px 10px; width: 150px; height: 32px; line-height: 32px; background: rgb(251, 250, 244); border: 1px solid rgb(227, 224, 205); color: rgb(153, 153, 153); border-radius: 5px;" type="text" value="逝者姓名" /><input class="search2" name="submit" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px 0px 0px 10px; padding: 0px; width: 32px; height: 32px; line-height: 32px; background: url('http://www.tiantang6.com/../images/searchan.png') no-repeat;" type="submit" value=" " /></form>
            </div>
        </div>
    </div>
    <div id="nav" style="margin: 0px; padding: 0px; height: 42px; background: rgb(239, 219, 167) url('http://www.tiantang6.com/../images/navborder.png') repeat-x; position: relative; overflow: hidden;">
        <ul style="margin: 0px auto; padding: 0px; list-style: none; position: relative; width: 1200px; max-width: 1200px; min-width: 1000px; height: 40px;">
            <li class="lock" style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none; font-size: 18px;">首页</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/memorial/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">网上纪念馆</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/quickreg/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">快速建馆</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/culture/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">民俗文化</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/life/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">生命文化</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/info/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">天堂资讯</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">帮助中心</a></li>
            <li style="margin: 0px; padding: 0px 18px; list-style: none; float: left; line-height: 40px;"><a href="http://www.tiantang6.com/about/" style="margin: 0px; padding: 0px; color: rgb(69, 26, 18); text-decoration: none; font-size: 18px;">关于天堂网</a></li>
        </ul>
        <div class="navbottom" style="margin: 0px; padding: 0px; clear: both; bottom: 0px; width: 1885px; height: 1px; background: rgb(239, 219, 167) url('http://www.tiantang6.com/../images/navborder.png') repeat-x center bottom;">
        </div>
    </div>
    <div id="mainbanner" style="margin: 0px; padding: 0px; width: 1885px; height: 320px; overflow: hidden; position: relative; z-index: 1;">
        <ul class="rslides f1660x649 rslides1" style="margin: 0px auto 0px -960px; padding: 0px; list-style: none; z-index: 100; position: relative; width: 1920px; height: 360px; left: 942.5px; overflow: hidden;">
            <li id="rslides1_s1" class="rslides1_on" style="margin: 0px; padding: 0px; list-style: none; width: 1920px; text-align: center; display: list-item; float: left; position: relative;"><a href="http://www.tiantang6.com/culture/special5005.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">
                <img alt="中秋节祭祀" src="http://www.tiantang6.com/images/mainbanner16816.jpg" style="border: 0px;" /></a></li>
        </ul>
        <ul class="rslides_tabs rslides1_tabs" style="margin: 0px; padding: 0px; list-style: none; position: absolute; z-index: 999; bottom: 18px; height: 18px; width: 1920px; left: 942.5px;">
            <li class="" style="margin: 3px 2px 0px; padding: 0px; list-style: none; width: 12px; height: 12px; float: left;"><a class="rslides1_s1" href="http://www.tiantang6.com/#" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; display: block; width: 12px; height: 12px; overflow: hidden; text-indent: 10em; background: url('http://www.tiantang6.com/../images/icon_1.png') no-repeat;">1</a></li>
            <li class="rslides_here" style="margin: 3px 2px 0px; padding: 0px; list-style: none; width: 12px; height: 12px; float: left;"><a class="rslides1_s2" href="http://www.tiantang6.com/#" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; display: block; width: 12px; height: 12px; overflow: hidden; text-indent: 10em; background: url('http://www.tiantang6.com/../images/icon_11.png') no-repeat;">2</a></li>
            <li class="" style="margin: 3px 2px 0px; padding: 0px; list-style: none; width: 12px; height: 12px; float: left;"><a class="rslides1_s3" href="http://www.tiantang6.com/#" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; display: block; width: 12px; height: 12px; overflow: hidden; text-indent: 10em; background: url('http://www.tiantang6.com/../images/icon_1.png') no-repeat;">3</a></li>
        </ul>
    </div>
    <div id="main" style="margin: 30px auto 0px; padding: 0px; clear: both; position: relative; width: 1885px; z-index: 1;">
        <div id="content" style="margin: 0px auto; padding: 0px; position: relative; width: 1200px; max-width: 1200px; min-width: 1000px; clear: both;">
            <div class="widthbig left" style="margin: 0px; padding: 0px; width: 852px; max-width: 860px; min-width: 700px; overflow: hidden; float: left;">
                <div class="newjidian" style="margin: 0px; padding: 0px; width: 852px; min-height: 350px; overflow: hidden;">
                    <div class="title" style="margin: 0px 0px 15px; padding: 0px; height: 40px; border-bottom: 1px solid rgb(220, 215, 194);">
                        <h3 class="f20" style="margin: 0px; padding: 0px; font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 18px; height: 40px; line-height: 30px; font-weight: 500; color: rgb(171, 88, 68); float: left;">最新祭奠</h3>
                        <div class="right" style="margin: 0px; padding: 0px; float: right; line-height: 30px; color: rgb(126, 111, 101);">
                            <a href="http://www.tiantang6.com/memorial/jn1001.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">祭奠祖先</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1002.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">纪念父母</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1003.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">兄弟姐妹</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1004.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">怀念爱人</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1005.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">缅怀亲属</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1006.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">伟人英雄烈士</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn1008.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">名人艺人</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/memorial/jn8000.html" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none;">更多追思</a></div>
                    </div>
                    <div class="jdlist" style="margin: 0px; padding: 0px; float: left; width: 852px;">
                        <ul style="margin: 0px; padding: 0px; list-style: none; float: left; width: 852px;">
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102115284" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="爱子阮小虎纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2014220115036.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                爱子阮小虎</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102172242" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="周欣钰纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2015121015521.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                周欣钰</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102190404" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="袁昇纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/20164191040.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                袁昇</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102229344" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="赵紫嫣纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t201692074744.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                赵紫嫣</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102231021" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="赵财纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/2016102414333.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                赵财</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102130257" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="周泽齐纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2015101574545.JPG" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                周泽齐</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102168084" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="余磊纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2015928725.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                余磊</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102146238" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="吕从阳纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t201411119482.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                吕从阳</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102079353" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="梁文梅纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/Mu201211312143.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                梁文梅</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102228228" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="王思语纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2016831114549.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                王思语</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102087660" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="章金娥纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/Mu2013323192127.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                章金娥</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102227676" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="李潇纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2016819231758.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                李潇</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://j.tiantang6.com/md/102176973" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="石富纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/t2016314202443.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                石富</a></li>
                            <li style="margin: 0px; padding: 5px 0px; list-style: none; float: left; width: 121.703px; height: 130px; text-align: center; line-height: 16.8px; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102072690" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none; font-size: 13px;" target="_blank">
                                <img alt="孙语浓纪念馆" border="0" height="90" src="http://www.tiantang6.com/uptupian/Mu201271121329.jpg" style="border: 1px solid rgb(220, 215, 194); margin-bottom: 2px; width: 84px; height: 90px; padding: 4px; background: rgb(251, 250, 244);" width="84" /><br />
                                孙语浓</a></li>
                        </ul>
                    </div>
                    <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                </div>
                <div class="jdly " style="margin: 0px; padding: 0px;">
                    <ul style="margin: 0px; padding: 0px; list-style: none; float: left;">
                        <li class="left" style="margin: 12px 0px 0px; padding: 0px; list-style: none; float: left; position: relative; width: 408.953px; height: 85px; border: 1px solid rgb(223, 223, 223); background: rgb(251, 250, 244); font-size: 13px;">
                            <img src="http://www.tiantang6.com/pic/4/63.jpg" style="border: 0px; float: left; padding: 13px 13px 0px; width: 60px; height: 60px;" /><p style="margin: 0px; padding: 12px; line-height: 20.8px;">
                                <a href="http://www.tiantang6.com/m/102172242/jidian.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank" title="钰钰，爸爸给娃娃点亮蜡烛，娃娃，一切安好！">钰钰，爸爸给娃娃点亮蜡烛，娃娃，一切安好！</a><span class="Apple-converted-space">&nbsp;</span><br />
                                [<a class="red" href="http://j.tiantang6.com/md/102172242" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;" target="_blank">周欣钰纪念馆</a>] 冰冰<span class="Apple-converted-space">&nbsp;</span><span class="c999" style="color: rgb(153, 153, 153);">22:35</span></p>
                            <div class="topjt" style="margin: 0px; padding: 0px; position: absolute; width: 15px; height: 9px; top: -8px; left: 30px; background: url('http://www.tiantang6.com/../images/topjt.png') no-repeat center bottom;">
                            </div>
                        </li>
                        <li class="right" style="margin: 12px 0px 0px; padding: 0px; list-style: none; float: right; position: relative; width: 408.953px; height: 85px; border: 1px solid rgb(223, 223, 223); background: rgb(251, 250, 244); font-size: 13px;">
                            <img src="http://www.tiantang6.com/pic/2/pc.jpg" style="border: 0px; float: left; padding: 13px 13px 0px; width: 60px; height: 60px;" /><p style="margin: 0px; padding: 12px; line-height: 20.8px;">
                                <a href="http://www.tiantang6.com/m/102115284/jidian.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank" title="晚安，小虎。">晚安，小虎。</a><span class="Apple-converted-space">&nbsp;</span><br />
                                [<a class="red" href="http://j.tiantang6.com/md/102115284" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;" target="_blank">爱子阮小虎纪念馆</a>] 小姐<span class="Apple-converted-space">&nbsp;</span><span class="c999" style="color: rgb(153, 153, 153);">22:35</span></p>
                            <div class="topjt" style="margin: 0px; padding: 0px; position: absolute; width: 15px; height: 9px; top: -8px; left: 30px; background: url('http://www.tiantang6.com/../images/topjt.png') no-repeat center bottom;">
                            </div>
                        </li>
                        <li class="left" style="margin: 12px 0px 0px; padding: 0px; list-style: none; float: left; position: relative; width: 408.953px; height: 85px; border: 1px solid rgb(223, 223, 223); background: rgb(251, 250, 244); font-size: 13px;">
                            <img src="http://www.tiantang6.com/pic/4/13.gif" style="border: 0px; float: left; padding: 13px 13px 0px; width: 60px; height: 60px;" /><p style="margin: 0px; padding: 12px; line-height: 20.8px;">
                                <a href="http://www.tiantang6.com/m/102190404/jidian.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank" title="晚安！">晚安！</a><span class="Apple-converted-space">&nbsp;</span><br />
                                [<a class="red" href="http://j.tiantang6.com/md/102190404" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;" target="_blank">袁昇纪念馆</a>] 冰冰<span class="Apple-converted-space">&nbsp;</span><span class="c999" style="color: rgb(153, 153, 153);">22:34</span></p>
                            <div class="topjt" style="margin: 0px; padding: 0px; position: absolute; width: 15px; height: 9px; top: -8px; left: 30px; background: url('http://www.tiantang6.com/../images/topjt.png') no-repeat center bottom;">
                            </div>
                        </li>
                        <li class="right" style="margin: 12px 0px 0px; padding: 0px; list-style: none; float: right; position: relative; width: 408.953px; height: 85px; border: 1px solid rgb(223, 223, 223); background: rgb(251, 250, 244); font-size: 13px;">
                            <img src="http://j.tiantang6.com/jipinimg/xiang/51.png" style="border: 0px; float: left; padding: 13px 13px 0px; width: 60px; height: 60px;" /><p style="margin: 0px; padding: 12px; line-height: 20.8px;">
                                <a href="http://www.tiantang6.com/m/102197745/jidian.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank" title="奶奶 我来看您了 天气转凉 注意添加衣服 最近爷爷有些身体不适 请您保佑爷爷身体健康 全家平平安安！">奶奶 我来看您了 天气转凉 注意添加衣服 最近爷爷有些身体不适 请您保佑爷爷...</a><span class="Apple-converted-space">&nbsp;</span><br />
                                [<a class="red" href="http://j.tiantang6.com/md/102197745" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;" target="_blank">张玉华纪念馆</a>] chen51***<span class="Apple-converted-space">&nbsp;</span><span class="c999" style="color: rgb(153, 153, 153);">22:34</span></p>
                            <div class="topjt" style="margin: 0px; padding: 0px; position: absolute; width: 15px; height: 9px; top: -8px; left: 30px; background: url('http://www.tiantang6.com/../images/topjt.png') no-repeat center bottom;">
                            </div>
                        </li>
                    </ul>
                    <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                </div>
                <div class="top20" style="margin: 20px 0px 0px; padding: 0px;">
                    <a href="http://www.tiantang6.com/info/news204.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">
                    <img alt="天堂网手机版纪念馆" class="adimg left" src="http://www.tiantang6.com/images/mobi_ad2.jpg" style="border: 1px solid rgb(235, 230, 211); background: rgb(251, 250, 244); padding: 4px; float: left;" width="47%" /></a><a href="http://www.tiantang6.com/info/news243.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;"><img alt="高仿真3D虚拟墓地" class="adimg right" src="http://www.tiantang6.com/images/main_ad2.jpg" style="border: 1px solid rgb(235, 230, 211); background: rgb(251, 250, 244); padding: 4px; float: right;" width="47%" /></a><div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                </div>
                <div class="wenhua  top50" style="margin: 50px 0px 0px; padding: 0px;">
                    <div class="whleft left" style="margin: 0px; padding: 0px; float: left; width: 408.953px;">
                        <div class="title" style="margin: 0px 0px 15px; padding: 0px; float: left; width: 408.953px; position: relative; height: 40px; border-bottom: 1px solid rgb(220, 215, 194);">
                            <h3 style="margin: 0px; padding: 0px; font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 18px; height: 40px; line-height: 30px; font-weight: 500; float: left;">民俗文化</h3>
                            <a class="right more" href="http://www.tiantang6.com/culture/" style="margin: 0px; padding: 0px 8px 0px 0px; color: rgb(153, 153, 153); text-decoration: none; float: right; font-size: 12px;">更多</a></div>
                        <ul class="newslist" style="margin: 0px; padding: 0px 10px; list-style: none; float: left; clear: both; position: relative; width: 408.953px;">
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article550.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="中元节为什么要放河灯？">中元节为什么要放河灯？</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article545.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="中元节各地的习俗">中元节各地的习俗</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article540.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="父亲不知父亲节">父亲不知父亲节</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article535.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="端午节的禁忌你知道多少？">端午节的禁忌你知道多少？</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article530.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="还记得那种小时候妈妈做的端午凉糕吗？">还记得那种小时候妈妈做的端午凉糕吗？</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article525.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="清明网上祭扫缅怀故人">清明网上祭扫缅怀故人</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article520.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="网上祭扫的观念争议">网上祭扫的观念争议</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article515.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="清明祭扫回归本意">清明祭扫回归本意</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article510.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="这个清明，上海市民面对网络祭扫依然纠结">这个清明，上海市民面对网络祭扫依然纠结</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a href="http://www.tiantang6.com/culture/article505.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="扫墓高峰已至，南通殡葬部门倡议文明低碳祭扫">扫墓高峰已至，南通殡葬部门倡议文明低碳祭扫</a></li>
                        </ul>
                    </div>
                    <div class="whright right" style="margin: 0px; padding: 0px; float: right; width: 408.953px;">
                        <div class="title" style="margin: 0px 0px 15px; padding: 0px; float: left; width: 408.953px; position: relative; height: 40px; border-bottom: 1px solid rgb(220, 215, 194);">
                            <h3 style="margin: 0px; padding: 0px; font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 18px; height: 40px; line-height: 30px; font-weight: 500; float: left;">祭文选登</h3>
                            <a class="right more" href="http://www.tiantang6.com/memorial/jiwen.html" style="margin: 0px; padding: 0px 8px 0px 0px; color: rgb(153, 153, 153); text-decoration: none; float: right; font-size: 12px;">更多</a></div>
                        <ul class="newslist" style="margin: 0px; padding: 0px 10px; list-style: none; float: left; clear: both; position: relative; width: 408.953px;">
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102146238/article_14023.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="写给另一边的你（六百二十一）">写给另一边的你（六百二十一）<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[吕从阳纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102168183/article_14022.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="多希望......">多希望......<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[肖元晖纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102196206/article_14021.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="想你">想你<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[何靖纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102230916/article_14020.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="致妈妈">致妈妈<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[刘淑芬纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102143544/article_14019.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="真正的富有，是你脸上的微笑">真正的富有，是你脸上的微笑<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[巩洪臣纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102143544/article_14018.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="真正的富有，是你脸上的微笑">真正的富有，是你脸上的微笑<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[巩洪臣纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102152046/article_14017.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="夜不能寐，心碎思念爱子刘一帆远行636">夜不能寐，心碎思念爱子刘一帆远...<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[爱子刘一帆-爱女于 凡纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102152046/article_14016.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="心碎思念爱子刘一帆远行635">心碎思念爱子刘一帆远行635<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[爱子刘一帆-爱女于 凡纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102146238/article_14014.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="写给另一边的你（六百二十）">写给另一边的你（六百二十）<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[吕从阳纪念馆]</span></a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 408.953px; font-size: 14px;"><a class="an_dian" href="http://www.tiantang6.com/m/102168183/article_14013.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" target="_blank" title="因为我们心心相印">因为我们心心相印<span class="Apple-converted-space">&nbsp;</span><span class="blue" style="color: rgb(31, 99, 116); font-size: 12px;">[肖元晖纪念馆]</span></a></li>
                        </ul>
                    </div>
                    <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                </div>
            </div>
            <div class="widthsmall right" style="margin: 0px; padding: 0px; width: 281px; overflow: hidden; float: right;">
                <div class="typebox2 bgcolor-c3" style="margin: 0px; padding: 0px; background-image: url('http://www.tiantang6.com/../images/styleborder2.png'); background-color: rgb(245, 234, 195);">
                    <h3 class="f20 textcenter" style="margin: 0px; padding: 0px; font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 20px; height: 40px; line-height: 60px; font-weight: 500; text-align: center; color: rgb(171, 88, 68);">用户登录</h3>
                    <div class="loginbox" style="margin: 0px; padding: 10px;">
                        <form id="loginForm" action="http://www.tiantang6.com/login/go" method="post" name="loginForm" style="margin: 0px auto; padding: 0px; width: 245px; position: relative; overflow: hidden;">
                            <ul style="margin: 0px; padding: 0px; list-style: none; width: 245px;">
                                <li style="margin: 0px; padding: 10px 0px 0px; list-style: none; width: 245px; height: 40px;">
                                    <label style="float: left; height: 30px; line-height: 30px;">
                                    用户名：</label><input id="F_user" class="inputbox right" maxlength="20" name="F_user" style="margin: 0px; padding: 0px; float: right; width: 180px; height: 28px; line-height: 28px; border: 1px solid rgb(226, 196, 162); vertical-align: middle; text-indent: 10px; font-size: 16px;" type="text" value="" /></li>
                                <li style="margin: 0px; padding: 10px 0px 0px; list-style: none; width: 245px; height: 40px;">
                                    <label style="float: left; height: 30px; line-height: 30px;">
                                    密&nbsp;&nbsp;码：</label><input id="F_pw" class="inputbox right" maxlength="20" name="F_pw" style="margin: 0px; padding: 0px; float: right; width: 180px; height: 28px; line-height: 28px; border: 1px solid rgb(226, 196, 162); vertical-align: middle; text-indent: 10px; font-size: 16px;" type="password" /></li>
                                <li class="s2" style="margin: 0px; padding: 5px 0px 0px; list-style: none; width: 245px; height: 35px; font-size: 13px;">
                                    <label style="float: left; height: 30px; line-height: 30px; color: rgb(102, 102, 102);">
                                    <input name="cExpires" style="margin: 0px; padding: 0px; width: 14px; height: 14px; vertical-align: middle;" type="checkbox" value="1" /><span class="Apple-converted-space">&nbsp;</span>30天内免登录</label><span class="right" style="float: right;"><a href="http://www.tiantang6.com/help/help179.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">忘记密码？</a></span></li>
                                <li style="margin: 0px; padding: 10px 0px 0px; list-style: none; width: 245px; height: 40px;">
                                    <input class="submit" name="submit2" onclick="if(document.loginForm.F_user.value.length&lt;3){alert('请输入用户名!'); return false;}if(document.loginForm.F_pw.value.length&lt;4){alert('请输入密码!'); return false;}" style="border-style: none; border-color: inherit; border-width: medium; margin: 0px; padding: 0px; width: 245px; height: 35px; background: url('http://www.tiantang6.com/../images/loginan.png') no-repeat center bottom; font-size: 20px; color: rgb(255, 255, 255); font-family: 寰蒋闆呴粦, 闆呴粦, yahei, 榛戜綋, Arial;" type="submit" value="登  录" /></li>
                            </ul>
                        </form>
                        <div class="tt clear" style="margin: 0px; padding: 0px; clear: both; font-size: 14px; line-height: 55px; text-align: center;">
                            <a class="red" href="http://www.tiantang6.com/register/" style="margin: 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none;">注册用户，免费建立网上纪念馆</a></div>
                    </div>
                    <div class="typeboxbottom" style="margin: 0px; padding: 0px; height: 1px; background-image: url('http://www.tiantang6.com/../images/styleborder2.png');">
                    </div>
                </div>
                <div class="todayjd typebox top50" style="margin: 50px 0px 0px; padding: 0px; background-image: url('http://www.tiantang6.com/../images/styleborder.png'); position: relative;">
                    <p style="margin: 0px; padding: 20px 0px; width: 281px; line-height: 21px; text-align: center;">
                        <strong style="font-size: 18px; font-weight: 500;">那年今日</strong><br />
                        TA们远去，成为天上彼星<br />
                        给人间留下无限的思念</p>
                    <ul class="glist" style="margin: 0px auto; padding: 0px; list-style: none; width: 252px;">
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102061944" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="王凤网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/Mu2012714125538.jpg" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>王凤</span></a></li>
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://j.tiantang6.com/md/102171855" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="陈云春网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/t2015125184042.jpg" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>陈云春</span></a></li>
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102019215" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="高长科网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/200933142820.jpg" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>高长科</span></a></li>
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://j.tiantang6.com/md/102086760" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="亲爱的小丫丫网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/Mu2013227225815.JPG" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>亲爱的小丫丫</span></a></li>
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102007548" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="林毓梅网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/Mu2012113174659.jpg" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>林毓梅</span></a></li>
                        <li style="margin: 5px 6px; padding: 0px; list-style: none; float: left; position: relative; width: 70px; height: 70px; border-radius: 50%; overflow: hidden;"><a href="http://www.tiantang6.com/mu/102044199" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">
                            <img alt="赵鸿刚网上纪念馆" height="110" src="http://www.tiantang6.com/uptupian/photo.jpg" style="border: 0px; width: 70px; height: 70px;" width="103" /><span>赵鸿刚</span></a></li>
                    </ul>
                    <p class="clear" style="margin: 0px; padding: 20px 0px; clear: both; width: 281px; line-height: 21px; text-align: center;">
                        <a class="gojd" href="http://www.tiantang6.com/memorial/today.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">+ 查看更多</a></p>
                    <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                    <div class="typeboxbottom" style="margin: 0px; padding: 0px; height: 1px; background-image: url('http://www.tiantang6.com/../images/styleborder.png');">
                    </div>
                </div>
                <div class="typebox top50" style="margin: 50px 0px 0px; padding: 0px; background-image: url('http://www.tiantang6.com/../images/styleborder.png');">
                    <div class="mainnews" style="margin: 0px; padding: 10px 15px 15px;">
                        <div class="title" style="margin: 0px; padding: 0px; width: 251px; position: relative;">
                            <h3 style="margin: 0px; padding: 0px; font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 18px; height: 40px; line-height: 30px; font-weight: 500; float: left;">天堂资讯</h3>
                            <a class="right more" href="http://www.tiantang6.com/info/" style="margin: 0px; padding: 0px 8px 0px 0px; color: rgb(153, 153, 153); text-decoration: none; float: right; font-size: 12px;">更多</a></div>
                        <ul class="newslist" style="margin: 0px; padding: 0px; list-style: none; float: left; clear: both; position: relative; width: 251px;">
                            <ol style="margin: 0px 0px 10px; padding: 0px 0px 10px; float: left; width: 251px; border-bottom: 1px dotted rgb(204, 204, 204);">
                                <a href="http://www.tiantang6.com/info/news213.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;" title="《殡葬绿皮书2014~2015》网络祭祀发展趋势研究">
                                <img height="70" src="http://www.tiantang6.com/UploadFile/news/201541154714.jpg" style="border: 0px; margin-right: 10px; float: left;" width="91" /><strong style="font-size: 14px; line-height: 21px;">《殡葬绿皮书2014~2015》网络祭祀发展趋势...</strong></a><br />
                                <span style="font-size: 12px; color: rgb(102, 102, 102);">2015年3月25日《殡葬绿...</span></ol>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news355.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="人民日报：互联网+传统文化，有创新也有消解">人民日报：互联网+传统文化，有创...</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news339.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="【天堂网报道】VR让往生者复现 清明节里“天堂来电”正在进入现实">【天堂网报道】VR让往生者复现 清...</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news347.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="中国网：清明扫墓“互联网+”四面开花 手机APP、微信齐上阵">中国网：清明扫墓“互联网+”四面...</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news331.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="九江：清明节低碳祭扫渐入人心 鲜花、网上祭扫受宠">九江：清明节低碳祭扫渐入人心 鲜...</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news323.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="文明祭扫可以给清明节一片“清明”">文明祭扫可以给清明节一片“清明...</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news315.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="天津：文明祭扫 传承美德">天津：文明祭扫 传承美德</a></li>
                            <li style="margin: 0px; padding: 0px; list-style: none; clear: both; float: left; line-height: 28px; height: 28px; width: 251px;"><a href="http://www.tiantang6.com/info/news307.html" style="margin: 0px; padding: 0px 0px 0px 10px; color: rgb(79, 79, 79); text-decoration: none; display: block; height: 28px; width: auto; background: url('http://www.tiantang6.com/../images/ico1.gif') no-repeat 0px 13px;" title="清明在即 唐山民政部门发出“文明祭扫”倡议书">清明在即 唐山民政部门发出“文明...</a></li>
                        </ul>
                        <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                        </div>
                    </div>
                    <div class="typeboxbottom" style="margin: 0px; padding: 0px; height: 1px; background-image: url('http://www.tiantang6.com/../images/styleborder.png');">
                    </div>
                </div>
                <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                </div>
            </div>
            <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
            </div>
        </div>
        <div class="contentbox top50" style="margin: 50px auto 0px; padding: 0px; position: relative; width: 1200px; max-width: 1200px; min-width: 1000px; clear: both;">
            <div class="link " style="margin: 0px; padding: 0px; border-bottom: 1px solid rgb(235, 230, 211); line-height: 35px;">
                <strong>常用链接：</strong><a href="http://www.tiantang6.com/tools/day.htm" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">阴阳转换万年历</a><a href="http://www.tiantang6.com/tools/gb.htm" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">汉字简体繁体转换</a><a href="http://www.tiantang6.com/tools/wb.htm" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">汉字拼音查询</a><a href="http://www.tiantang6.com/tools/weather.htm" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">天气预报</a><a href="http://www.tiantang6.com/culture/c1007.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">中国节日大全</a><a href="http://www.tiantang6.com/culture/c1012.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">丧葬文书范文</a><a href="http://www.tiantang6.com/culture/c1057.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">讣告</a><a href="http://www.tiantang6.com/culture/c1058.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">唁电</a><a href="http://www.tiantang6.com/culture/c1059.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">悼词</a><a href="http://www.tiantang6.com/culture/c1060.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">答谢词</a><a href="http://www.tiantang6.com/culture/c1061.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">挽联</a><a href="http://www.tiantang6.com/culture/c1062.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">碑文</a><a href="http://www.tiantang6.com/culture/c1063.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">墓志铭</a><a href="http://www.tiantang6.com/culture/c1064.html" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;">祭文</a></div>
            <div class="link top5" style="margin: 5px 0px 0px; padding: 0px; border-bottom: 1px solid rgb(235, 230, 211); line-height: 35px;">
                <strong>友情链接：</strong><a href="http://www.mca.gov.cn/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国民政部</a><a href="http://www.zgbzxh.org/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国殡葬协会</a><a href="http://www.thanos.org/index.php?lang=4" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">国际殡葬协会</a><a href="http://www.wenming.cn/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国文明网</a><a href="http://www.redcross.org.cn/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国红十字会</a><a href="http://www.chinacharityfederation.org/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中华慈善总会</a><a href="http://www.mcprc.gov.cn/" rel="nofollow" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国文化部</a><a href="http://www.tsingming.com/" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">清明网</a><a href="http://www.readlishi.com/" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">中国历史</a><a href="http://xl.39.net/" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">39心理网</a><a href="http://www.zgnongli.com/" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">农历网</a><a href="http://www.ankang.biz/" style="margin: 0px; padding: 0px 7px; color: rgb(79, 79, 79); text-decoration: none;" target="_blank">安康视窗</a></div>
            <div class="fortiantang6 top20" style="margin: 20px 0px 0px; padding: 0px; font-size: 16px; text-align: center; color: rgb(171, 88, 68); line-height: 50px;">
                天堂网——为逝去的亲人故友建立网上纪念馆、打造永恒的生命档案、进行网上祭奠、延续生命故事……</div>
        </div>
    </div>
    <div id="footer" class="top30" style="margin: 30px 0px 0px; padding: 0px; border-top: 1px solid rgb(220, 215, 194);">
        <div class="footermenu" style="margin: 0px auto; padding: 20px 0px; width: 1200px; max-width: 1200px; min-width: 1000px;">
            <ul style="margin: 0px 60px 0px 0px; padding: 0px 0px 0px 10px; list-style: none; float: left;">
                <ol style="margin: 0px 0px 10px; padding: 0px; font-weight: 500;">
                    <a href="http://www.tiantang6.com/about/" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none; font-size: 16px;">关于天堂网</a></ol>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/about/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">天堂网介绍</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/info/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">天堂资讯</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/about/agreement.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">服务条款</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/about/contact.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">联系我们</a></li>
            </ul>
            <ul style="margin: 0px 60px 0px 0px; padding: 0px 0px 0px 10px; list-style: none; float: left;">
                <ol style="margin: 0px 0px 10px; padding: 0px; font-weight: 500;">
                    <a href="http://www.tiantang6.com/" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none; font-size: 16px;">网上祭祀</a></ol>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/memorial/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">网上纪念馆</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/quickreg/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">免费建馆</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/memorial/jiwen.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">纪念文章</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/memorial/photo.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">纪念相册</a></li>
            </ul>
            <ul style="margin: 0px 60px 0px 0px; padding: 0px 0px 0px 10px; list-style: none; float: left;">
                <ol style="margin: 0px 0px 10px; padding: 0px; font-weight: 500;">
                    <a href="http://www.tiantang6.com/culture/" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none; font-size: 16px;">民俗文化</a></ol>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/culture/c1001.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">传统文化</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/culture/c1004.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">国学精粹</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/culture/c1008.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">姓氏文化</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/culture/c1009.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">殡葬文化</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/culture/c1015.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">宗教信仰</a></li>
            </ul>
            <ul style="margin: 0px 60px 0px 0px; padding: 0px 0px 0px 10px; list-style: none; float: left;">
                <ol style="margin: 0px 0px 10px; padding: 0px; font-weight: 500;">
                    <a href="http://www.tiantang6.com/life/" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none; font-size: 16px;">生命文化</a></ol>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/life/c2001.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">生命教育</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/life/c2002.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">智慧人生</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/life/c2003.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">和谐家庭</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/life/c2004.html" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">生命传奇</a></li>
            </ul>
            <ul style="margin: 0px 60px 0px 0px; padding: 0px 0px 0px 10px; list-style: none; float: left;">
                <ol style="margin: 0px 0px 10px; padding: 0px; font-weight: 500;">
                    <a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(126, 111, 101); text-decoration: none; font-size: 16px;">帮助中心</a></ol>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">建馆帮助</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">会员帮助</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">怎样建纪念馆</a></li>
                <li style="margin: 0px; padding: 0px; list-style: none;"><a href="http://www.tiantang6.com/help/" style="margin: 0px; padding: 0px; color: rgb(79, 79, 79); text-decoration: none;">怎样网上祭奠</a></li>
            </ul>
            <div class="footkf" style="margin: 0px; padding: 0px 0px 0px 30px; float: right; width: 165px; height: 140px; line-height: 50px; font-size: 16px; border-left: 1px dotted rgb(223, 223, 223);">
                天堂网服务电话<br />
                <img src="http://www.tiantang6.com/images/kftel.png" style="border: 0px;" /><br />
                <a class="footkfan" href="http://www.tiantang6.com/help/#online" style="margin: 20px 0px 0px; padding: 0px; color: rgb(171, 88, 68); text-decoration: none; display: block; width: 167px; height: 30px; line-height: 28px; font-size: 14px; background: url('http://www.tiantang6.com/../images/footerkfan.jpg') no-repeat; text-align: center;">在线客服</a></div>
            <div class="footwx" style="margin: 0px; padding: 0px 20px 0px 0px; float: right; width: 140px; text-align: center; font-size: 12px;">
                <img src="http://www.tiantang6.com/images/bottom-wx.jpg" style="border: 0px;" /><br />
                天堂网微信公众平台</div>
            <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
            </div>
        </div>
        <div class="footerbottom" style="margin: 0px; padding: 0px; background: rgb(119, 106, 98) url('http://www.tiantang6.com/../images/footerbbb.jpg') repeat-x center top;">
            <div class="copyright" style="margin: 0px auto; padding: 20px 10px 2px; width: 960px; color: rgb(231, 228, 219); text-align: center; font-family: Arial, 宋体;">
                <p style="margin: 0px; padding: 6px 0px;">
                    Copyright © 2006 - 2016 www.tiantang6.com All Rights Reserved.<br />
                    版权所有<span class="Apple-converted-space">&nbsp;</span><a href="http://www.tiantang6.com/" style="margin: 0px; padding: 0px; color: rgb(231, 228, 219); text-decoration: none;">天堂网</a><span class="Apple-converted-space">&nbsp;</span><a class="tb" href="http://www.tiantang6.com/about/copyright.html" style="margin: 0px; padding: 0px; color: rgb(231, 228, 219); text-decoration: none;">版权声明</a><span class="Apple-converted-space">&nbsp;</span><a class="tb" href="http://www.tiantang6.com/about/sitemap.html" style="margin: 0px; padding: 0px; color: rgb(231, 228, 219); text-decoration: none;">网站地图</a><br />
                    <a href="http://www.miibeian.gov.cn/" rel="nofollow" style="margin: 0px; padding: 0px; color: rgb(231, 228, 219); text-decoration: none;" target="_blank">粤ICP备11057806号</a></p>
                <p style="margin: 0px; padding: 6px 0px;">
                    <img height="32" src="http://www.tiantang6.com/images/bottom-ico1.jpg" style="border: 0px;" width="32" /><span class="Apple-converted-space">&nbsp;</span><img height="32" src="http://www.tiantang6.com/images/bottom-ico2.jpg" style="border: 0px;" width="32" /></p>
            </div>
        </div>
    </div>
    <div id="scrollnav" class="scrollnav" style="margin: 0px; padding: 0px; width: 46px; position: fixed; top: 320px; right: 2px; z-index: 1000;">
        <div class="me" onmouseout="this.className='me'" onmouseover="this.className='over'" style="margin: 0px 0px 2px; padding: 0px; height: 40px; width: 40px; color: rgb(79, 79, 79); font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 248, 248);">
            <a class="an" href="http://www.tiantang6.com/#" style="margin: 0px; padding: 0px; color: rgb(139, 139, 122); text-decoration: none; display: block; height: 40px; width: 40px; line-height: 40px; overflow: hidden; text-align: center; font-size: 14px; background: rgb(239, 219, 167); border-radius: 5px;">客服</a></div>
        <div class="me" onmouseout="this.className='me'" onmouseover="this.className='over'" style="margin: 0px 0px 2px; padding: 0px; height: 40px; width: 40px; color: rgb(79, 79, 79); font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 248, 248);">
            <a class="an" href="http://www.tiantang6.com/#" style="margin: 0px; padding: 0px; color: rgb(139, 139, 122); text-decoration: none; display: block; height: 40px; width: 40px; line-height: 40px; overflow: hidden; text-align: center; font-size: 14px; background: rgb(239, 219, 167); border-radius: 5px;">转告</a></div>
        <div class="me" onmouseout="this.className='me'" onmouseover="this.className='over'" style="margin: 0px 0px 2px; padding: 0px; height: 40px; width: 40px; color: rgb(79, 79, 79); font-family: 微软雅黑, 雅黑, yahei, 黑体, Arial; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 248, 248);">
            <br class="Apple-interchange-newline" />
        </div>
    </div>
    <form id="form1" runat="server">
    <div>
    
    </div>
    </form>
</body>
</html>
